### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by guacke** [CCQC/chem-8950#3]
I really like your notes and would like to contribute back to them. However, I cannot currently do this as this repository is under exclusive copyright (https://choosealicense.com/no-permission/). Are you open to adding an open-source license to this repository (possibly an MIT license https://choosealicense.com/licenses/mit/ or a GNU license https://choosealicense.com/licenses/gpl-3.0 /)?

**Comment by avcopan** [comment]
I'm fine with adding one of those licenses! I wrote the notes, but am not actively involved in maintaining them anymore. @jturney is this okay with you?

**Comment by jturney** [comment]
Sounds good to me!

**Comment by avcopan** [comment]
Okay, I've added the license file, if you could accept the pull request @jturney.

@guacke Hope this helps!

**Comment by guacke** [comment]
@avcopan and @jturney Thank you for adding the Apache license!
